Repository Haid-Faiz/Java_Hacktoberfest, pull requests merged in 2020-10, with the labels that each got.

#5 used one print function instead of two
  src/Main.java
Labels: Hacktoberfest, good first issue, hacktoberfest-accepted

#7 Removing unnecessary array and replacing it with Math.random
  src/Main.java
Labels: Hacktoberfest, hacktoberfest-accepted

#6 Create Java code for random class
  Java code for random class
  java code for random class
Labels: Hacktoberfest, Hacktoberfest2020, good first issue, hacktoberfest-accepted

#4 Added input for max number and function to sum two random numbers generated from it
  out/Main.class
  src/Main.java
Labels: Hacktoberfest, hacktoberfest-accepted
